version: '3.8'
services:
  cache:
    container_name: trainconnections-api-redis-cache
    image: redis:6.2-alpine
    restart: unless-stopped
    # ports:
    #   - '33001:6379'
    command: redis-server --loglevel warning
    # volumes:
    #   - ...:/data

  trainconnections-api:
    container_name: trainconnections-api
    image: wardbeyens/api-trainconnections:latest
    environment:
      - REDIS_URI=redis://trainconnections-api-redis-cache
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - cache
